from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class PermissionModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Main data
    register_user = models.BooleanField(default=False, null=True)
    modify_permission = models.BooleanField(default=False, null=True)
    dashboard = models.BooleanField(null=True)
    company = models.BooleanField('Company', null=True)
    create_company = models.BooleanField(null=True)
    company_table = models.BooleanField(null=True)
    inward = models.BooleanField(null=True)
    inward_form = models.BooleanField(null=True)
    vehicle_entry = models.BooleanField(null=True)
    mother_table = models.BooleanField(null=True)
    slitted_table = models.BooleanField(null=True)
    pipe_inward = models.BooleanField(null=True)
    planning = models.BooleanField(null=True)
    coil_planning = models.BooleanField(null=True)
    slitt_plan = models.BooleanField(null=True)
    polish_plan = models.BooleanField(null=True)
    coil_plan = models.BooleanField(null=True)
    pipe_planning = models.BooleanField(null=True)
    slitting = models.BooleanField(null=True)
    pipe = models.BooleanField(null=True)
    first_obse = models.BooleanField(null=True)
    inprocess = models.BooleanField(null=True)
    tubemill = models.BooleanField(null=True)
    tubemill_movement = models.BooleanField(null=True)
    polish_inspection = models.BooleanField(null=True)
    polish_movement = models.BooleanField(null=True)
    dispatch = models.BooleanField(null=True)
    coil_dispatch = models.BooleanField(null=True)
    scrap_data = models.BooleanField(null=True)
    pipe_sales = models.BooleanField(null=True)
    coil_sales = models.BooleanField(null=True)
    sales_scrap = models.BooleanField(null=True)
    data_process = models.BooleanField(null=True)
    entry_vehicle = models.BooleanField(null=True)
    process_inward = models.BooleanField(null=True)
    production = models.BooleanField(null=True)
    slitting_process = models.BooleanField(null=True)
    failed_challan = models.BooleanField(null=True)
    process_dispatch = models.BooleanField(null=True)
    process_booking = models.BooleanField(null=True)
    process_sales_dispatch = models.BooleanField(null=True)
    sales = models.BooleanField(null=True)
    company_list = models.BooleanField(null=True)
    booking_sales = models.BooleanField(null=True)
    order = models.BooleanField(null=True)
    coil_order = models.BooleanField(null=True)
    warehouse = models.BooleanField(null=True)
    mothercoil = models.BooleanField(null=True)
    slittedcoil = models.BooleanField(null=True)
    scrap = models.BooleanField(null=True)
    challan = models.BooleanField(null=True)
    pc_pipe = models.BooleanField(null=True)
    download = models.BooleanField(null=True)

    def __str__(self):
        return self.user.username
